// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD07OCh78rUizyRRYOPukbpg_8x8UAjQTA',
    appId: '1:975276530329:web:c232b74b4e3e98f3863608',
    messagingSenderId: '975276530329',
    projectId: 'therapylink69',
    authDomain: 'therapylink69.firebaseapp.com',
    storageBucket: 'therapylink69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh71Q1hN_Ol9trmteBqo1jr0aOrYh-f1s',
    appId: '1:975276530329:android:a77c42db70a5181b863608',
    messagingSenderId: '975276530329',
    projectId: 'therapylink69',
    storageBucket: 'therapylink69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73LEPg4H019YFq9TadgIBLlYhiX6H0Io',
    appId: '1:975276530329:ios:464f3e9630757742863608',
    messagingSenderId: '975276530329',
    projectId: 'therapylink69',
    storageBucket: 'therapylink69.firebasestorage.app',
    iosClientId: '975276530329-t2gac7jo6gne8qd3bvagehcm70jpfabb.apps.googleusercontent.com',
    iosBundleId: 'com.example.therapylink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73LEPg4H019YFq9TadgIBLlYhiX6H0Io',
    appId: '1:975276530329:ios:464f3e9630757742863608',
    messagingSenderId: '975276530329',
    projectId: 'therapylink69',
    storageBucket: 'therapylink69.firebasestorage.app',
    iosClientId: '975276530329-t2gac7jo6gne8qd3bvagehcm70jpfabb.apps.googleusercontent.com',
    iosBundleId: 'com.example.therapylink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD07OCh78rUizyRRYOPukbpg_8x8UAjQTA',
    appId: '1:975276530329:web:8dfea90c37bdf95a863608',
    messagingSenderId: '975276530329',
    projectId: 'therapylink69',
    authDomain: 'therapylink69.firebaseapp.com',
    storageBucket: 'therapylink69.firebasestorage.app',
  );

}